server:
  port: 20102

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/asdb
    username: garden
    password: garden
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
#logging:
#  level:
#    root: DEBUG
#    org.springframework: DEBUG
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

jwt:
  token:
    secret:
      access: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
    duration: 60
